# Import environment variables from .env files in repo
set dotenv-load := true

# Define specific variables for just to use in the justfiles
PACKAGE := "{{cookiecutter.package}}"
REPOSITORY := "{{cookiecutter.repository}}"
SOURCES := "src"
TESTS := "tests"

# Define default command when user types just in terminal
default:
    @just --list

# Import defined justfiles
import 'automation/docker.just'
import 'automation/document.just'
import 'automation/initialize.just'
import 'automation/package.just'
import 'automation/quality.just'
import 'automation/remove.just'
import 'automation/version.just'
