FROM ghcr.io/astral-sh/uv:python{{python_version}}-bookworm
COPY dist/*.whl .
RUN uv pip install --system *.whl
RUN useradd -m app
USER app
COPY config app/config.yml
ENTRYPOINT [{{package}}]
CMD ["/app/config.yml"]
